/**
 * 从 gong-wang-fu.json 导出 D1 可执行的 seed SQL（供 wrangler d1 execute --remote 使用）
 */
import { writeFileSync } from 'node:fs';
import gongWangFuData from '../api/data/gong-wang-fu.json';
import { MVP_COMPANION_IDS } from '../api/data/companions.js';
import type { WalkArea } from '../api/data/walk-area-types.js';

const area = gongWangFuData as WalkArea;
const lines: string[] = [
  '-- Generated by npm run db:export-sql',
  'DELETE FROM walk_acts;',
  'DELETE FROM walk_jokes;',
  'DELETE FROM walk_fences;',
  'DELETE FROM walk_areas;',
  '',
];

function sqlValue(value: string | number | null | undefined): string {
  if (value == null) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

lines.push(`INSERT INTO walk_areas (id, name, area_tag, sim_base_lat, sim_base_lng, sim_coord_step_lat, sim_radius_meters) VALUES (${[
  sqlValue(area.id),
  sqlValue(area.name),
  sqlValue(area.areaTag),
  sqlValue(area.simulation?.baseLat ?? null),
  sqlValue(area.simulation?.baseLng ?? null),
  sqlValue(area.simulation?.coordStepLat ?? null),
  sqlValue(area.simulation?.radiusMeters ?? null),
].join(', ')});`);

area.fences.forEach((fence, fenceIndex) => {
  lines.push(
    `INSERT INTO walk_fences (id, area_id, label, trigger_hint, lat, lng, radius_meters, sort_order) VALUES (${[
      sqlValue(fence.id),
      sqlValue(area.id),
      sqlValue(fence.label),
      sqlValue(fence.triggerHint ?? null),
      sqlValue(fence.location.lat),
      sqlValue(fence.location.lng),
      sqlValue(fence.location.radiusMeters),
      sqlValue(fenceIndex),
    ].join(', ')});`,
  );

  for (const companionId of MVP_COMPANION_IDS) {
    const jokes = fence.byCompanion[companionId]?.jokes ?? [];
    jokes.forEach((joke, jokeIndex) => {
      lines.push(
        `INSERT INTO walk_jokes (id, fence_id, companion_id, label, sort_order) VALUES (${[
          sqlValue(joke.id),
          sqlValue(fence.id),
          sqlValue(companionId),
          sqlValue(joke.label ?? null),
          sqlValue(jokeIndex),
        ].join(', ')});`,
      );

      joke.acts.forEach((act, actIndex) => {
        lines.push(
          `INSERT INTO walk_acts (fence_id, companion_id, joke_id, act_index, version_id, content, label) VALUES (${[
            sqlValue(fence.id),
            sqlValue(companionId),
            sqlValue(joke.id),
            sqlValue(actIndex),
            sqlValue(act.versionId),
            sqlValue(act.content),
            sqlValue(act.label ?? null),
          ].join(', ')});`,
        );
      });
    });
  }
});

const outPath = new URL('./d1-seed-remote.sql', import.meta.url);
writeFileSync(outPath, `${lines.join('\n')}\n`);
console.log('joyjoy exported', outPath.pathname);
